name: mayo_flutter_push_notifications
description: Flutter plugin for push notifications
version: 0.0.1
homepage: https://mayosoftware.es

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:

  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^16.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0