name: mayo_flutter_push_notifications
description: Flutter plugin for push notifications
version: 1.0.3
homepage: https://mayosoftware.es

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:

  bloc: null
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.4.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^18.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.1.5
  freezed: ^2.2.0
  json_serializable: ^6.1.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
  melos: ^6.1.0

scripts:
  build: "flutter pub run build_runner build --delete-conflicting-outputs"
  build-watch: "flutter pub run build_runner watch"